In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [4]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent = dataset[['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes']]

In [7]:
independent

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [8]:
dependent=dataset[["charges"]]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR

param_grid = {
    'kernel': ['rbf', 'poly', 'sigmoid', 'linear'],
    'C': [10, 100, 1000, 2000, 3000],
    'gamma': ['auto', 'scale']
}

grid = GridSearchCV(
    SVR(),
    param_grid,
    refit=True,
    verbose=3,
    n_jobs=-1
)

# Fitting the model for Grid Search
grid.fit(X_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [12]:
# print best parameter after tuning
# print(grid.best_params_)

re = grid.cv_results_

print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}:

In [13]:
table = pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.087183,0.003326,0.032446,0.001757,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.019706,0.040699,-0.099080,-0.060829,-0.084383,-0.036777,5.642583e-02,35
1,0.062848,0.006684,0.011005,0.001284,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.229547,0.296925,0.186989,0.224262,0.182470,0.224038,4.109350e-02,32
2,0.078336,0.006629,0.013616,0.001110,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.136037,0.162617,0.022401,0.063774,0.038939,0.084754,5.499023e-02,33
3,0.063020,0.005167,0.011839,0.003087,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.804737,0.828142,0.765030,0.787370,0.757488,0.788553,2.588042e-02,23
4,0.083610,0.012459,0.033420,0.001819,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.020393,0.040661,-0.099483,-0.060671,-0.084825,-0.036785,5.670390e-02,36
5,0.063564,0.005770,0.011530,0.001043,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.215035,0.297915,0.197439,0.220036,0.193610,0.224807,3.790866e-02,31
6,0.072481,0.008040,0.015261,0.001320,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.133719,0.162747,0.023510,0.063242,0.040367,0.084717,5.415590e-02,34
7,0.057843,0.004213,0.011351,0.001786,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.804737,0.828142,0.765030,0.787370,0.757488,0.788553,2.588042e-02,23
8,0.071848,0.003588,0.034411,0.000560,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.461495,0.434313,0.297883,0.358736,0.292537,0.368993,6.903710e-02,27
9,0.062269,0.004791,0.012998,0.001520,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.828424,0.849385,0.887313,0.868037,0.816834,0.849999,2.562630e-02,21
10,0.077804,0.004904,0.014683,0.001744,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.793563,0.802905,0.736267,0.761569,0.743286,0.767518,2.656991e-02,26
11,4.692537,0.623594,0.004964,0.000439,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.388629e-12,7
12,0.072343,0.004011,0.038073,0.001473,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.465543,0.434056,0.295167,0.359794,0.289417,0.368795,7.130521e-02,28
13,0.073239,0.007087,0.014615,0.001475,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.819463,0.849550,0.889314,0.867049,0.819504,0.848976,2.718000e-02,22
14,0.093269,0.003900,0.016438,0.002553,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.794175,0.803123,0.739674,0.764141,0.745869,0.769396,2.536165e-02,25
15,5.060567,0.369717,0.004791,0.000985,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.388629e-12,7
16,0.100180,0.004908,0.039343,0.002457,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.971894,0.920836,0.923120,0.932548,0.883362,0.926352,2.828960e-02,19
17,0.142783,0.032566,0.012391,0.001080,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.917105,0.933066,0.950054,0.938980,0.908979,0.929637,1.483023e-02,18
18,0.081953,0.005594,0.016174,0.001194,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.340892,0.178435,0.276406,0.042379,0.464716,0.260566,1.433397e-01,30
19,5.110160,0.816470,0.003415,0.000498,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.170610e-12,5
20,0.104352,0.009455,0.040037,0.002121,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.972879,0.920751,0.922100,0.933011,0.881731,0.926094,2.915239e-02,20
21,0.135767,0.023883,0.012233,0.000997,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.915140,0.933184,0.950574,0.938842,0.910493,0.929647,1.491532e-02,17
22,0.074886,0.004545,0.014275,0.001160,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.363995,0.257937,0.254729,0.062132,0.449475,0.277654,1.298779e-01,29
23,5.117960,1.095816,0.003887,0.000819,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.170610e-12,5
24,0.144853,0.018695,0.042658,0.001839,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.990202,0.954455,0.961844,0.970152,0.920013,0.959333,2.300492e-02,13
25,0.279800,0.056403,0.013931,0.000839,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.942301,0.956288,0.963745,0.954490,0.941338,0.951632,8.597869e-03,16
26,0.093294,0.004804,0.017580,0.001035,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.192419,-1.308074,-1.224554,-2.056886,-0.621458,-1.280678,4.579866e-01,38
27,4.765937,1.981552,0.002855,0.000084,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.187339e-12,3
28,0.181962,0.023503,0.057330,0.010742,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.990437,0.954386,0.961315,0.970334,0.919115,0.959118,2.338455e-02,14
29,0.332514,0.082682,0.020413,0.003108,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.939884,0.956399,0.964547,0.954221,0.943511,0.951712,8.945723e-03,15
30,0.127799,0.003824,0.025424,0.002207,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.032485,-1.316123,-1.295404,-1.942140,-0.672003,-1.251631,4.163824e-01,37
31,4.582561,1.454855,0.003866,0.001132,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,4.187339e-12,3
32,0.229107,0.035151,0.048183,0.006613,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.993596,0.966447,0.976680,0.980935,0.932307,0.969993,2.075758e-02,9
33,0.673002,0.282546,0.012666,0.001150,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.959371,0.970259,0.974784,0.966342,0.959826,0.966116,5.956593e-03,11
34,0.091430,0.007073,0.017885,0.001679,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-3.500851,-3.836691,-3.956199,-5.177963,-2.349648,-3.764270,9.067692e-01,40
35,4.650103,1.252714,0.003573,0.000600,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.956048e-12,1
36,0.191108,0.016174,0.044370,0.004977,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.993744,0.966406,0.976357,0.981028,0.931474,0.969802,2.108453e-02,10
37,0.658761,0.237194,0.013488,0.000468,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.956822,0.970379,0.975610,0.965852,0.961233,0.965979,6.610592e-03,12
38,0.099928,0.005330,0.017745,0.001633,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-3.200023,-3.820570,-4.100743,-5.048273,-2.433635,-3.720649,8.768692e-01,39
39,3.981255,0.706121,0.002313,0.000569,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.956048e-12,1

In [17]:
age_input = float(input("Age:"))
bmi_input = float(input("BMI:"))
children_input = float(input("children:"))
sex_male_input = int(input("Sex Male 0 or 1:"))
smoker_yes_input = int(input("Smoker Yes 0 or 1:"))

Age: 32
BMI: 42
children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [21]:
Future_Prediction = grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

ValueError: X has 5 features, but SVR is expecting 6 features as input.